ARG BASE_IMAGE=${BASE_IMAGE}
FROM ${BASE_IMAGE}

ENV TEST_USER macs

RUN apt-get update -qq && \
  apt-get install -yq \
  python3 \
  python3-pip \
  python3-setuptools \
  python3-wheel\
  procps

RUN useradd -m "${TEST_USER}"
USER "${TEST_USER}"
WORKDIR /build
COPY requirements.txt .
ENV PATH "/home/${TEST_USER}/.local/bin:${PATH}"
RUN pip3 install --user cython --no-cache-dir
RUN pip3 install --user --upgrade -r requirements.txt --no-cache-dir
