#!/usr/bin/env bash
 
## pyprofile: profile Python script
 
## $Revision$
## Copyright 2011 Michael M. Hoffman <mmh1@uw.edu>
## Modified by Tao Liu: Correctly get the command name.
 
set -o nounset
set -o pipefail
set -o errexit
 
if [ $# == 0 ]; then
    echo usage: "$0" CMDLINE...
    exit 2
fi
 
MAIN=`basename $1`
 
PROF="${MAIN}.$(date +%Y%m%dT%H%M%S).prof"
 
python -m cProfile -o "$PROF" "$@"
python -m pstats "$PROF"
