#!/usr/bin/env python

"""Module Description: Test functions that write wiggle, bedGraph, R model
and diagnosis outputs (MACS3.IO.OutputWriter).

This code is free software; you can redistribute it and/or modify it
under the terms of the BSD License (see the file LICENSE included with
the distribution).
"""

import gzip
import logging
import re
from types import SimpleNamespace

import numpy as np
import pytest

from MACS3.IO.OutputWriter import (zwig_write,
                                   zbdg_write,
                                   model2r_script,
                                   diag_write)
from MACS3.Utilities.Constants import MACS_VERSION

# ------------------------------------
# Helpers
# ------------------------------------


class FakeTrack:
    """Minimal stand-in for FWTrack: ``get_chr_names`` and
    ``get_locations_by_chr`` returning (plus, minus) int32 arrays."""

    def __init__(self, tags):
        self._tags = tags

    def get_chr_names(self):
        return set(self._tags)

    def get_locations_by_chr(self, chrom):
        return (np.array(self._tags[chrom], dtype="i4"),
                np.array([], dtype="i4"))


def _gunzip(path):
    with gzip.open(path, "rt") as fh:
        return fh.read()


def _wig_track_line(prefix, chrom, space=10):
    return ('track type=wiggle_0 name="%s_%s" description="Extended tag '
            'pileup from MACS version %s for every %d bp"\n'
            % (prefix, chrom, MACS_VERSION, space))


def _bdg_track_line(prefix, chrom):
    return ('track type=bedGraph name="%s_%s" description="Extended tag '
            'pileup from MACS version %s"\n' % (prefix, chrom, MACS_VERSION))


# ------------------------------------
# model2r_script
# ------------------------------------

def _model(**kwargs):
    """Fake PeakModel with the attribute types of a real one: int32 lines,
    float64 correlations, int alternative_d list."""
    base = dict(plus_line=np.array([1, 2, 1], dtype="i4"),
                minus_line=np.array([0, 1, 3], dtype="i4"),
                ycorr=np.array([0.25, 0.5, -0.125]),
                xcorr=np.array([-1.0, 0.0, 1.0]),
                alternative_d=[100, 150],
                d=100)
    base.update(kwargs)
    return SimpleNamespace(**base)


def _r_script(p, m, ycorr, xcorr, altd_comma_space, name, altd_comma):
    return ("# R script for Peak Model\n"
            "#  -- generated by MACS\n"
            "p <- c(%s)\n"
            "m <- c(%s)\n"
            "ycorr <- c(%s)\n"
            "xcorr <- c(%s)\n"
            "altd  <- c(%s)\n"
            "x <- seq.int((length(p)-1)/2*-1,(length(p)-1)/2)\n"
            "pdf('%s_model.pdf',height=6,width=6)\n"
            "plot(x,p,type='l',col=c('red'),main='Peak Model',"
            "xlab='Distance to the middle',ylab='Percentage')\n"
            "lines(x,m,col=c('blue'))\n"
            "legend('topleft',c('forward tags','reverse tags'),lty=c(1,1,1),"
            "col=c('red','blue'))\n"
            "plot(xcorr,ycorr,type='l',col=c('black'),main='Cross-Correlation',"
            "xlab='Lag between + and - tags',ylab='Correlation')\n"
            "abline(v=altd,lty=2,col=c('red'))\n"
            "legend('topleft','alternative lag(s)',lty=2,col='red')\n"
            "legend('right','alt lag(s) : %s',bty='n')\n"
            "dev.off()\n"
            % (p, m, ycorr, xcorr, altd_comma_space, name, altd_comma))


def test_model2r_script_exact(tmp_path):
    out = tmp_path / "x_model.r"
    model2r_script(_model(), str(out), "sample")
    # p = [1, 2, 1] -> 100 * p / 4 = [25, 50, 25] percent
    # m = [0, 1, 3] -> 100 * m / 4 = [0, 25, 75] percent
    assert out.read_text() == _r_script("25.0,50.0,25.0", "0.0,25.0,75.0",
                                        "0.25,0.5,-0.125", "-1.0,0.0,1.0",
                                        "100, 150", "sample", "100,150")


def test_model2r_script_plain_lists_single_alt_d(tmp_path):
    out = tmp_path / "m.r"
    model = _model(plus_line=[3, 1], minus_line=[1, 1, 2, 0],
                   ycorr=[1, 2], xcorr=[5, 6], alternative_d=[200])
    model2r_script(model, str(out), "a/b")
    # p: [75, 25]; m: 100 * [1, 1, 2, 0] / 4 = [25, 25, 50, 0]; only the
    # first len(p) values of m are written
    assert out.read_text() == _r_script("75.0,25.0", "25.0,25.0", "1,2",
                                        "5,6", "200", "a/b", "200")


def test_model2r_script_empty_lines(tmp_path):
    out = tmp_path / "m.r"
    model2r_script(_model(plus_line=[], minus_line=[], ycorr=[], xcorr=[],
                          alternative_d=[]), str(out), "e")
    assert out.read_text() == _r_script("", "", "", "", "", "e", "")


def test_model2r_script_zero_sum_raises(tmp_path):
    with pytest.raises(ZeroDivisionError):
        model2r_script(_model(plus_line=[0, 0], minus_line=[1, 1]),
                       str(tmp_path / "m.r"), "z")


def test_model2r_script_overwrites(tmp_path):
    out = tmp_path / "m.r"
    out.write_text("old\n" * 100)
    model2r_script(_model(), str(out), "sample")
    assert out.read_text().startswith("# R script for Peak Model\n")
    assert "old" not in out.read_text()


def test_model2r_script_missing_attribute(tmp_path):
    with pytest.raises(AttributeError):
        model2r_script(SimpleNamespace(plus_line=[1]), str(tmp_path / "m.r"),
                       "x")


# ------------------------------------
# diag_write
# ------------------------------------

def test_diag_write_exact(tmp_path):
    out = tmp_path / "diag.txt"
    diag_write(str(out), [["10-20", 5, 0.123, 0.456, 0.789],
                          ["20-inf", 12, 1.0, 99.994, 0.0]])
    # three metric columns -> sampling levels 90%, 80%, 70%; "%.2f" each
    assert out.read_text() == (
        "FC range\t# of Peaks\tcover by sampling 90%\t80%\t70%\n"
        "10-20\t5\t0.12\t0.46\t0.79\n"
        "20-inf\t12\t1.00\t99.99\t0.00\n")


def test_diag_write_no_metrics(tmp_path):
    out = tmp_path / "diag.txt"
    diag_write(str(out), [("all", 3.7)])
    # "%d" truncates 3.7 to 3
    assert out.read_text() == "FC range\t# of Peaks\tcover by sampling %\nall\t3\n"


def test_diag_write_eleven_levels(tmp_path):
    out = tmp_path / "diag.txt"
    diag_write(str(out), [["x", 1] + [0.5] * 11])
    levels = "%\t".join(str(90 - 10 * i) for i in range(11)) + "%"
    assert out.read_text().splitlines()[0] == \
        "FC range\t# of Peaks\tcover by sampling " + levels
    assert levels.endswith("0%\t-10%")


def test_diag_write_empty_raises(tmp_path):
    with pytest.raises(IndexError):
        diag_write(str(tmp_path / "diag.txt"), [])


def test_diag_write_ragged_rows_raise(tmp_path):
    with pytest.raises(TypeError, match="not enough arguments"):
        diag_write(str(tmp_path / "diag.txt"), [["a", 1, 0.5], ["b", 2]])


# ------------------------------------
# zwig_write
# ------------------------------------

def _log_text(record):
    """Message of a log record without MemoryLogger's "[N MB] " prefix.

    OutputWriter does not import MACS3.Utilities.Logger itself, so its
    logger is a MemoryLogger only when another MACS3 module imported
    Logger first (as in a real macs3 run, or earlier tests in the same
    session). Stripping the prefix keeps these tests order-independent.
    """
    return re.sub(r"^\[\d+ MB\] ", "", record.getMessage())


def test_zwig_write_no_chromosomes(tmp_path):
    sub = tmp_path / "wig"
    zwig_write(FakeTrack({}), str(sub), "pre", 20)
    assert sub.is_dir()
    assert list(sub.iterdir()) == []


def test_zwig_write_single_no_chromosomes(tmp_path, caplog):
    sub = tmp_path / "wig"
    with caplog.at_level(logging.INFO, logger="MACS3.IO.OutputWriter"):
        zwig_write(FakeTrack({}), str(sub), "pre_afterfiting", 20, space=25,
                   single=True)
    assert [p.name for p in sub.iterdir()] == ["pre_afterfiting_all.wig.gz"]
    assert _gunzip(sub / "pre_afterfiting_all.wig.gz") == \
        _wig_track_line("pre", "all", space=25)
    assert [_log_text(r) for r in caplog.records] == \
        ["write to a wiggle file", "compress the wiggle file using gzip..."]


def test_zwig_write_existing_directory_raises(tmp_path):
    with pytest.raises(FileExistsError):
        zwig_write(FakeTrack({}), str(tmp_path), "pre", 20)


def test_zwig_write_chromosome_without_tags(tmp_path):
    sub = tmp_path / "wig"
    zwig_write(FakeTrack({"chr1": []}), str(sub), "pre", 20)
    assert [p.name for p in sub.iterdir()] == ["pre_chr1.wig.gz"]
    assert _gunzip(sub / "pre_chr1.wig.gz") == \
        _wig_track_line("pre", "chr1") + "variableStep chrom=chr1 span=10\n"


# ------------------------------------
# zbdg_write
# ------------------------------------

def test_zbdg_write_no_chromosomes(tmp_path):
    sub = tmp_path / "bdg"
    zbdg_write(FakeTrack({}), str(sub), "pre", 20)
    assert sub.is_dir()
    assert list(sub.iterdir()) == []


def test_zbdg_write_single_no_chromosomes(tmp_path, caplog):
    sub = tmp_path / "bdg"
    with caplog.at_level(logging.INFO, logger="MACS3.IO.OutputWriter"):
        zbdg_write(FakeTrack({}), str(sub), "x_afterfiting", 20, single=True)
    assert [p.name for p in sub.iterdir()] == ["x_afterfiting_all.bdg.gz"]
    assert _gunzip(sub / "x_afterfiting_all.bdg.gz") == \
        _bdg_track_line("x", "all")
    assert [_log_text(r) for r in caplog.records] == \
        ["write to a bedGraph file", "compress the bedGraph file using gzip..."]


def test_zbdg_write_existing_directory_raises(tmp_path):
    with pytest.raises(FileExistsError):
        zbdg_write(FakeTrack({}), str(tmp_path), "pre", 20)


def test_zbdg_write_chromosome_without_tags(tmp_path):
    sub = tmp_path / "bdg"
    zbdg_write(FakeTrack({"chr1": []}), str(sub), "pre", 20)
    assert [p.name for p in sub.iterdir()] == ["pre_chr1.bdg.gz"]
    assert _gunzip(sub / "pre_chr1.bdg.gz") == _bdg_track_line("pre", "chr1")


