# Use an official Python runtime as a parent image
FROM python:2.7-slim

# Set the working directory to /
WORKDIR /

# Copy the current directory contents into the container at /app
COPY bin/ /usr/local/bin/
COPY lib/ /usr/local/lib/python2.7/site-packages/

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org numpy

# Define environment variable
ENV NAME MACS2

# Run app.py when the container launches
CMD ["macs2", "-h"]
